spring:
  application:
    name: algasensors-temperature-monitoring
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    listener:
      simple:
        prefetch: 4 # define quantas mensagens são pegar pelo consumidor
        retry:
          enabled: true
          initial-interval: 10s
          max-interval: 30s
          multiplier: 2
          max-attempts: 3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
    settings:
      web-allow-others: true
  datasource:
    url: jdbc:h2:file:~/algasensors-temperature-monitoring-db;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    driverClassName: org.h2.Driver
    username: sa
    password: 123

server:
  port: 8082
